### ISSUE TITLE
ERROR in example

### ISSUE THREAD

**Issue by prometheusloong** [wjian8/psvcp_v1.01#4]
Hi,

I have tested the example by `python Construct_pan_and_Call_sv.py -t 20 -o ./ -fqd fq_dir_example genome_gff_dir_example genome_list`

But there are some errors as below:
`Input delta file: pan_dir_result/ref0_Lemont_0-2M/ref0_Lemont_0-2M.delta
Output prefix: pan_dir_result/ref0_Lemont_0-2M/ref0_Lemont_0-2M.bed
Unique anchor length: 1000
Minimum variant size to call: 50
Maximum variant size to call: 10000000
Logging progress updates in pan_dir_result/ref0_Lemont_0-2M/progress.log
1. Filter delta file
2. Finding variants between alignments
Loaded 86 alignments
3. Finding variants within alignments
4. Combine variants between and within alignments
Warning messages:
1: Removed 6 rows containing missing values (geom_bar). 
2: Removed 6 rows containing missing values (geom_bar). 
index file pan_dir_result/ref0.fa.fai not found, generating...
Error in checkForRemoteErrors(val) : 
  one node produced an error: 'nchar()' requires a character vector
Calls: parLapply ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
Traceback (most recent call last):
  File "/public/home/zcyu/software/psvcp_v1.01-main/construct_pan_script/11gene_in_pv_screen.py", line 7, in <module>
    df = pd.read_csv(sys.argv[1],sep='\t',header=None)
  File "/public/home/zcyu/software/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/public/home/zcyu/software/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/public/home/zcyu/software/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/public/home/zcyu/software/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/public/home/zcyu/software/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/public/home/zcyu/software/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/public/home/zcyu/software/anaconda3/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/public/home/zcyu/software/anaconda3/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'pan_dir_result/Lemont_0-2M.gff.in_pv'
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'pan_dir_result/Lemont_0-2M.gff_gene_absolutly.in_pv': No such file or directory
Execution halted
cat: pan_dir_result/Lemont_0-2M.gene_absolutly_in_pv.gff: No such file or directory`

**Comment by wjian8** [comment]
```
python3 $path_of_the_pipeline/Construct_pan_and_Call_sv.py 
    genome_gff_dir 
    genome_list 
    -fqd fq_dir 
    -o    population_hmp     #output name 
```

Error in checkForRemoteErrors(val) :
one node produced an error: 'nchar()' requires a character vector
Calls: parLapply ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted

Can you make sure you have R v3.5.0 or later (https://www.r-project.org/) and packages: -hash -parallel -snowfall?
please don't set the thread to 20. The example data isn't the big data. (The default thread is 12.)
